### PR TITLE
Update clause_2_conformance.adoc

### PR DESCRIPTION
**Pull request by chris-little**
typos

### CODE REVIEW

**Comment by cmheazel** [comment]
This pull request corrects spelling errors.

**Comment by chris-little** [comment]
The Oxford English Dictionary (all editions) prefers 'z' to 's'.

**Comment by bradh** [comment]
> The Oxford English Dictionary (all editions) prefers 'z' to 's'.
FWIW, the Oxford Australian Reference Dictionary (1992) says "organisation". I can live with either though.

**Comment by chris-little** [comment]
Thanks, Brad,

I have learnt something! But of course, OGC policy is to use American English, however that is defined>

Chris

**Pull request merged**
